language: go

go:
  - 1.9.x

before_install:
  - go get -t -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script: make tests
